---
ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
ansible_ssh_user: centos
ansible_ssh_private_key_file: "{{ lookup('env', 'SSH_AUTH_SERVER') }}"
mysql_auth_psw: "{{ lookup('env', 'MYSQL_AUTH_PSW') }}"
mysql_auth_usr: "{{ lookup('env', 'MYSQL_AUTH_USR') }}"
docker_image_name: "{{ lookup('env', 'DOCKERHUB_AUTH_USR') }}/{{ lookup('env', 'IMAGE_NAME') }}"
docker_image_tag: "{{ lookup('env', 'IMAGE_TAG') }}"
docker_username: "{{ lookup('env', 'DOCKERHUB_AUTH_USR') }}"
docker_password: "{{ lookup('env', 'DOCKERHUB_AUTH_PSW') }}"
local_deploy_dir: ../deploy
remote_deploy_dir: .