---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: paymybuddy-mysql
  labels:
    app: paymybuddy
spec:
  selector:
    matchLabels:
      app: paymybuddy
      tier: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: paymybuddy
        tier: mysql
    spec:
      containers:
      - image: mysql:9
        name: mysql
        env:
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: app-paymybuddy-pass
              key: mysql_user
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-paymybuddy-pass
              key: mysql_password
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-paymybuddy-pass
              key: mysql_root_password
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-persistent-storage