---
apiVersion: v1
kind: Service
metadata:
  name: paymybuddy-mysql
  labels:
    app: paymybuddy
spec:
  ports:
    - port: 3306
      targetPort: 3306
      protocol: TCP
  selector:
    app: paymybuddy
    tier: mysql
  type:  ClusterIP