---
- name: Init Folder To Deploy
  hosts: localhost
  tasks:
    - name: Init Docker Compose
      template:
        src: docker-compose.yml.j2
        dest: ../deploy/docker-compose.yml
    - name: Init Env For Spring Boot
      template:
        src: paymybuddy.env.j2
        dest: ../deploy/env/paymybuddy.env
    - name: Create secrets directory
      file:
        path: ../deploy/secrets
        state: directory
        mode: '0755'
    - name: Init Secret Password For Database
      template:
        src: db_password.txt.j2
        dest: ../deploy/secrets/db_password.txt
    - name: Init Secret User For Database
      template:
        src: db_user.txt.j2
        dest: ../deploy/secrets/db_user.txt
    

- name: Deploy Application
  hosts: "{{ deploy_host }}"
  become: true
  vars:
    ansible_python_interpreter: /usr/bin/python3
  pre_tasks:
    - name: Install python 3.6 and pip3
      yum:
        name: python36
        state: present
    - name: Setup docker python
      ansible.builtin.pip:
        name: 
          - docker==4.4.4
          - docker-compose
        state: present
        executable: pip3
  tasks:
    - name: Copy "deploy" folder to client
      ansible.builtin.copy:
        src: "{{ local_deploy_dir }}"
        dest: "{{ remote_deploy_dir }}"
    - name: Connect to Docker Hub
      community.docker.docker_login:
        username: "{{ docker_username }}"
        password: "{{ docker_password }}"
        registry: "https://index.docker.io/v1/"
    - name: Retrieve image from Docker Hub
      community.docker.docker_image:
        name: "{{ docker_image_name }}"
        tag: "{{ docker_image_tag }}"
        source: pull
    - name: Stop and delete Docker Compose containers
      community.docker.docker_compose:
        project_src: deploy
        state: absent
    - name: Starting Docker Compose containers in detached mode
      community.docker.docker_compose:
        project_src: deploy
        state: present